services:
  spotify-rep:
    build: .
    container_name: spotify-rep
    ports:
      - "5000:5000"
    environment:
      - MUSIC_PATH=/music
      - THUMBNAIL_PATH=/app/thumbnails
      - DATA_PATH=/app/data
      - FLASK_ENV=production
    volumes:
      # NAS mount on web-vm -> inside container as /music
      - /mnt/nas/quran:/data/quran:ro

      # keep these persistent on the VM
      - ./data:/app/data
      - ./thumbnails:/app/thumbnails
      - ./music:/music:ro
    restart: unless-stopped
