services:
  spotify-rep:
    build: .
    container_name: spotify-rep
    ports:
      - "5000:5000"
    environment:
      - MUSIC_PATH=/music
      - DB_PATH=/app/data/music.db
      - THUMBNAIL_PATH=/app/thumbnails
    volumes:
      - ./data:/app/data
      - ./thumbnails:/app/thumbnails
    restart: unless-stopped
